"""Recover completed scheduler cells from an interrupted served-event log.

The original run only wrote its result tables after finishing an entire project.
This utility turns all complete method groups in that partial log into run rows,
and copies only those complete groups into a clean legacy event shard.
"""
from __future__ import annotations

import csv
import gzip
from pathlib import Path

import numpy as np
import pandas as pd

import run_cannier as RC

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "results/cannier"
SOURCE = OUT / "served.csv.gz"
LEGACY = OUT / "served_legacy.csv.gz"


def _pool(project):
    return RC.pool_read(OUT / "pools" / f"{project}.npz")


def _oracle_values(project, seed, p):
    bank = RC.SequenceBank(project, seed, p["item_id"], p["F"])
    bank.audit_all()
    seqs = np.stack([bank.sequence(i) for i in range(len(p["item_id"]))])
    prefix = seqs.cumsum(axis=1, dtype=np.int32)
    nn = np.arange(1, 2501, dtype=np.float64)
    width = np.sqrt(np.log(2.0 * nn * (nn + 1.0) / RC.DELTA) / (2.0 * nn))
    crossed = (prefix / nn[None, :] - width[None, :]) > RC.TAU
    has_crossed = crossed.any(axis=1)
    first_k = np.where(has_crossed, crossed.argmax(axis=1) + 1, -1)
    positive = p["F"] / 2500 > RC.TAU
    never = int(np.sum(positive & ~has_crossed))
    values = {}
    for ratio in RC.RATIOS:
        count, _ = RC.exact_oracle(p, project, seed,
                                   ratio * float(p["B_pass"]), bank,
                                   first_k, never)
        values[ratio] = (int(count), never)
    return values


def _thresholds():
    vals = np.zeros(2501, dtype=np.int16)
    for n in range(1, 2501):
        vals[n] = next((s for s in range(1, n + 1)
                        if RC.V.confirmed_sn(s, n, RC.TAU, RC.DELTA)), n + 1)
    return vals


def _run_row(key, item_ids, counts, confirmed, cost_sum, p, ids, thresholds,
             oracle_count):
    project, seed, ratio, method = key
    ref = p["F"] / 2500 > RC.TAU
    ref_int = ref & (p["F"] < 2500)
    mask = confirmed
    tp = int(np.sum(mask & ref)); tpi = int(np.sum(mask & ref_int))
    npos = int(ref.sum()); nint = int(ref_int.sum())
    n_candidates = len(p["item_id"])
    budget = float(ratio * p["B_pass"])
    n_exec = int(counts.sum())
    # Old selectors did not serialize CPU timing, fallback calls, or HDoC
    # elimination state. Those fields are regenerated by the resume pass.
    n_eliminated = np.nan if method == "HDoC-Sampling" else 0
    n_fallback = np.nan if method in {"ReproAlloc", "ReproAlloc (uncapped)"} else 0
    return {
        "benchmark": "CANNIER-Shuffle", "project": project,
        "method": method, "r": ratio, "seed": seed,
        "n_candidates": n_candidates, "n_pos": npos, "n_pos_int": nint,
        "confirmed_total": int(mask.sum()), "confirmed_pos": tp,
        "confirmed_pos_int": tpi,
        "false_conf": int(np.sum(mask & ~ref)),
        "recall": tp / npos if npos else 0.,
        "recall_int": tpi / nint if nint else 0., "n_exec": n_exec,
        "B": budget, "B_used": cost_sum,
        "overtime": max(0., cost_sum - budget), "sched_cpu_s": np.nan,
        "n_eliminated": n_eliminated, "n_fallback": n_fallback,
        "init_completed": bool(np.all(counts > 0)),
        "oracle_count": oracle_count,
    }


def main():
    thresholds = _thresholds()
    pool_cache = {}
    oracle_cache = {}
    rows = []
    group_key = None
    group_lines = []
    group_counts = group_sums = group_confirmed = None
    group_cost_sum = 0.
    group_n = 0
    group_ids = None
    group_thresholds = thresholds
    recovered_events = 0
    dropped_last_events = 0

    with gzip.open(SOURCE, "rt", newline="", encoding="utf-8") as src, \
            gzip.open(LEGACY, "wt", newline="", encoding="utf-8",
                      compresslevel=1) as dst:
        reader = csv.DictReader(src)
        writer = csv.writer(dst)
        writer.writerow(["project", "seed", "r", "method", "item_id", "k", "y"])

        def finish_group(keep):
            nonlocal recovered_events, dropped_last_events
            if group_key is None:
                return
            if not keep:
                dropped_last_events += group_n
                return
            project, seed, ratio, method = group_key
            p = pool_cache[project]
            oracle_key = (project, seed)
            if oracle_key not in oracle_cache:
                oracle_cache[oracle_key] = _oracle_values(project, seed, p)
            oracle_count = oracle_cache[oracle_key][ratio][0]
            rows.append(_run_row(group_key, group_ids, group_counts,
                                 group_confirmed, group_cost_sum, p, group_ids,
                                 thresholds, oracle_count))
            writer.writerows(group_lines)
            recovered_events += group_n

        try:
            for row in reader:
                key = (row["project"], int(row["seed"]), float(row["r"]),
                       row["method"])
                if key != group_key:
                    finish_group(keep=True)
                    group_key = key
                    project = key[0]
                    if project not in pool_cache:
                        pool_cache[project] = _pool(project)
                    p = pool_cache[project]
                    group_ids = {int(item): i for i, item in enumerate(p["item_id"])}
                    k = len(p["item_id"])
                    group_counts = np.zeros(k, dtype=np.int32)
                    group_sums = np.zeros(k, dtype=np.int32)
                    group_confirmed = np.zeros(k, dtype=bool)
                    group_cost_sum = 0.
                    group_n = 0
                    group_lines = []
                item_id = int(row["item_id"])
                i = group_ids[item_id]
                execution = int(row["k"])
                outcome = int(row["y"])
                group_counts[i] += 1
                group_sums[i] += outcome
                if not group_confirmed[i] and group_sums[i] >= thresholds[execution]:
                    group_confirmed[i] = True
                group_cost_sum += float(pool_cache[key[0]]["cost"][i])
                group_n += 1
                group_lines.append((key[0], key[1], key[2], key[3],
                                    item_id, execution, outcome))
        except (EOFError, OSError):
            # The source intentionally ends in an incomplete gzip member.
            pass

        # The final group has no following group boundary, so it may have been
        # interrupted while being written. Drop it and rerun that method cell.
        finish_group(keep=False)

    pd.DataFrame(rows).to_csv(OUT / "runs.csv", index=False)
    oracle_rows = []
    confirm_rows = []
    for (project, seed), values in oracle_cache.items():
        p = pool_cache[project]
        positives = int(np.sum(p["F"] / 2500 > RC.TAU))
        for ratio, (count, never) in values.items():
            oracle_rows.append({"project": project, "seed": seed, "r": ratio,
                                "oracle_count": count,
                                "oracle_recall": count / positives if positives else 0.})
            confirm_rows.append({"project": project, "seed": seed, "r": ratio,
                                 "n_positive_never_cross": never})
    pd.DataFrame(oracle_rows).to_csv(OUT / "oracle.csv", index=False)
    pd.DataFrame(confirm_rows).to_csv(OUT / "confirmability.csv", index=False)
    print(f"recovered_runs={len(rows)}; recovered_events={recovered_events}; "
          f"dropped_trailing_events={dropped_last_events}; "
          f"legacy_log={LEGACY}")


if __name__ == "__main__":
    main()
