# -*- coding: utf-8 -*-
"""Soft-budget overtime audit (paper Section 2.1 / Protocol).

Computed ONLY from the stored data shipped in this package (no experiment
is re-run):

  Part 1  overtime statistics per (benchmark, budget, method), aggregated
          from the stored run-level CSVs:
            results/01_optimistic_core/{amini,sensodat}/*_main.csv
            results/optimistic_scorecost_check/*_osc_check.csv
          `overtime` is recomputed as max(0, B_used - B) and checked against
          the stored field.
  Part 2  "does the final overrun execution add a confirmation?" for
          ReproAlloc, answered per run from the stored per-execution
          decision logs (logs/optimistic_ercc/{amini,sensodat}/main/).
          Per-execution time is reconstructed from the recorded durations:
            - Amini: the seed-specific pool order is rebuilt from the frozen
              harness seed (data/amini_transfuser_canonical.csv only);
            - SensoDat: deterministic recorded duration per scenario, which
              requires data/sensodat_fresh.npz (NOT shipped, see
              data/README.md). When the archive is absent the SensoDat rows
              are skipped with a note and the shipped
              results/overtime_final_execution_check.csv remains the final
              artifact for them.
  Part 3  the same question for ALL schedulers at the Amini 20% budget,
          answered from the stored per-execution replay traces
          (results/engineering_value_check/_replay_visits_20pct.csv).
          That intermediate is regenerated by
          scripts/build_engineering_value.py (offline, from shipped data);
          run it first if the file is absent.

Outputs:
  results/overtime_audit.csv
  results/overtime_final_execution_check.csv
  results/overtime_final_execution_check_amini20.csv
  reports/overtime_audit.md
"""
import glob
import os
import sys

import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))

RES1 = os.path.join(ROOT, "results", "01_optimistic_core")
OSCD = os.path.join(ROOT, "results", "optimistic_scorecost_check")
LOGS = os.path.join(ROOT, "logs", "optimistic_ercc")
EV = os.path.join(ROOT, "results", "engineering_value_check")
OUT_R = os.path.join(ROOT, "results")
OUT_REP = os.path.join(ROOT, "reports")
NPZ = os.path.join(ROOT, "data", "sensodat_fresh.npz")
os.makedirs(OUT_R, exist_ok=True)
os.makedirs(OUT_REP, exist_ok=True)

RENAME = {"ReproAlloc-Optimistic": "ReproAlloc", "ReproAlloc": "Mean Planning"}
DROP = {"ReproAlloc-OA"}
BENCH = {"amini": "Amini-TransFuser", "sensodat": "SensoDat-replay"}

L = []


def log(msg=""):
    print(msg, flush=True)
    L.append(msg)


# ---------------------------------------------------- 1. all methods stats ---
frames = []
a = pd.read_csv(os.path.join(RES1, "amini", "amini_optimistic_main.csv"))
frames.append(pd.DataFrame({
    "benchmark": BENCH["amini"], "budget": a.budget_frac,
    "method": a.method, "unit": a.seed, "rep": 0,
    "budget_s": a.budget_s, "time_used_s": a.time_used_s,
    "overtime_s": a.overtime_s, "confirmed": a.confirmed,
    "executions": a.executions}))
ao = pd.read_csv(os.path.join(OSCD, "amini_osc_check.csv"))
ao = ao[ao.method == "OptimisticScoreCost"]
frames.append(pd.DataFrame({
    "benchmark": BENCH["amini"], "budget": ao.budget_frac,
    "method": ao.method, "unit": ao.seed, "rep": 0,
    "budget_s": ao.budget_s, "time_used_s": ao.time_used_s,
    "overtime_s": ao.overtime_s, "confirmed": ao.confirmed,
    "executions": ao.executions}))
s = pd.read_csv(os.path.join(RES1, "sensodat", "sensodat_optimistic_main.csv"))
frames.append(pd.DataFrame({
    "benchmark": BENCH["sensodat"], "budget": s.time_frac,
    "method": s.method, "unit": s.split_id, "rep": s.rep,
    "budget_s": s.budget_s, "time_used_s": s.time_used,
    "overtime_s": s.overtime, "confirmed": s.confirmed,
    "executions": s.executions}))
so = pd.read_csv(os.path.join(OSCD, "sensodat_osc_check.csv"))
so = so[so.method == "OptimisticScoreCost"]
frames.append(pd.DataFrame({
    "benchmark": BENCH["sensodat"], "budget": so.time_frac,
    "method": so.method, "unit": so.split_id, "rep": so.rep,
    "budget_s": so.budget_s, "time_used_s": so.time_used,
    "overtime_s": so.overtime, "confirmed": so.confirmed,
    "executions": so.executions}))

df = pd.concat(frames, ignore_index=True)
df["overtime_recomputed"] = (df.time_used_s - df.budget_s).clip(lower=0.0)
max_diff = float((df.overtime_recomputed - df.overtime_s).abs().max())
df.method = df.method.replace(RENAME)
df = df[~df.method.isin(DROP)].copy()
df["overtime_frac"] = df.overtime_s / df.budget_s

g = (df.groupby(["benchmark", "budget", "method"], as_index=False)
       .agg(n_runs=("overtime_s", "size"),
            n_overrun=("overtime_s", lambda x: int((x > 0).sum())),
            mean_overtime_s=("overtime_s", "mean"),
            max_overtime_s=("overtime_s", "max"),
            mean_overtime_frac=("overtime_frac", "mean"),
            max_overtime_frac=("overtime_frac", "max")))
g = g.sort_values(["benchmark", "budget", "method"]).reset_index(drop=True)
g.to_csv(os.path.join(OUT_R, "overtime_audit.csv"), index=False,
         float_format="%.6g")
log("# Overtime audit (soft non-preemptive budget)")
log()
log("Computation: `overtime = max(0, B_used - B)` per run, from the stored")
log("main-experiment result CSVs. No experiment was re-run. The stored")
log(f"overtime field and the recomputed value agree (max abs diff "
    f"{max_diff:.1e} s).")
log()
log("## Per benchmark x budget x method")
log()
log("| benchmark | budget | method | runs | overrun | mean OT (s) | "
    "max OT (s) | mean OT/budget | max OT/budget |")
log("|---|---|---|---|---|---|---|---|---|")
for _, r in g.iterrows():
    log(f"| {r.benchmark} | {r.budget*100:.0f}% | {r.method} | {int(r.n_runs)} "
        f"| {int(r.n_overrun)} | {r.mean_overtime_s:.1f} "
        f"| {r.max_overtime_s:.1f} | {r.mean_overtime_frac:.5f} "
        f"| {r.max_overtime_frac:.5f} |")
log()

# ------------------------------ 2. ReproAlloc final-exec from decision logs ---
import experiment_amini_finite_trace as H  # noqa: E402

routes = H.load_routes()
main_am = pd.read_csv(os.path.join(RES1, "amini", "amini_optimistic_main.csv"))
main_sd = pd.read_csv(os.path.join(RES1, "sensodat",
                                   "sensodat_optimistic_main.csv"))

rows = []
for p in sorted(glob.glob(os.path.join(LOGS, "amini", "main", "*.csv"))):
    base = os.path.basename(p)
    seed = int(base.split("_")[1].replace("seed", ""))
    tf = float(base.split("_")[2].replace("b", "").replace(".csv", ""))
    orders = H.make_orders(routes, seed)
    d = pd.read_csv(p)
    visits = {}
    durs = []
    for arm in d.arm:
        v = visits.get(arm, 0)
        durs.append(routes[arm].durations[orders[arm][v]])
        visits[arm] = v + 1
    d["dur"] = durs
    d["cumtime"] = np.cumsum(d["dur"])
    ref = main_am[(main_am.seed == seed) & (main_am.budget_frac == tf)
                  & (main_am.method == "ReproAlloc-Optimistic")].iloc[0]
    time_ok = abs(d.cumtime.iloc[-1] - ref.time_used_s)
    exec_ok = int(len(d) == ref.executions)
    last = d.iloc[-1]
    prev = d[d.arm == last.arm].iloc[:-1]
    newly = bool(last.confirmed == 1
                 and (len(prev) == 0 or prev.confirmed.max() == 0))
    rows.append({"benchmark": BENCH["amini"], "unit": seed, "rep": 0,
                 "budget": tf, "budget_s": ref.budget_s,
                 "time_used_reconstructed": d.cumtime.iloc[-1],
                 "time_used_main_csv": ref.time_used_s,
                 "abs_time_diff": time_ok, "exec_count_match": exec_ok,
                 "overtime_s": d.cumtime.iloc[-1] - ref.budget_s,
                 "last_exec_overrun": bool(d.cumtime.iloc[-1] > ref.budget_s),
                 "last_exec_new_confirmation": newly})

have_npz = os.path.exists(NPZ)
if have_npz:
    npz = np.load(NPZ, allow_pickle=True)
    dur_raw = npz["duration_s"].astype(float)
    dur = np.where(np.isnan(dur_raw) | (dur_raw <= 0),
                   np.nanmedian(dur_raw), dur_raw)
    gen = npz["generator"].astype(int)
    tgt = np.sort(np.flatnonzero(gen == 1))
    for p in sorted(glob.glob(os.path.join(LOGS, "sensodat", "main",
                                           "*.csv"))):
        base = os.path.basename(p).replace(".csv", "")
        tok = base.split("_")
        sid = int(tok[1].replace("split", ""))
        tf = float(tok[2].replace("b", ""))
        rep = int(tok[3].replace("r", ""))
        d = pd.read_csv(p)
        durs = dur[tgt[d.arm.values]]
        d["dur"] = durs
        d["cumtime"] = np.cumsum(d["dur"])
        ref = main_sd[(main_sd.split_id == sid) & (main_sd.time_frac == tf)
                      & (main_sd.rep == rep)
                      & (main_sd.method == "ReproAlloc-Optimistic")].iloc[0]
        time_ok = abs(d.cumtime.iloc[-1] - ref.time_used)
        exec_ok = int(len(d) == ref.executions)
        last = d.iloc[-1]
        prev = d[d.arm == last.arm].iloc[:-1]
        newly = bool(last.confirmed == 1
                     and (len(prev) == 0 or prev.confirmed.max() == 0))
        rows.append({"benchmark": BENCH["sensodat"], "unit": sid, "rep": rep,
                     "budget": tf, "budget_s": ref.budget_s,
                     "time_used_reconstructed": d.cumtime.iloc[-1],
                     "time_used_main_csv": ref.time_used,
                     "abs_time_diff": time_ok, "exec_count_match": exec_ok,
                     "overtime_s": d.cumtime.iloc[-1] - ref.budget_s,
                     "last_exec_overrun": bool(d.cumtime.iloc[-1]
                                               > ref.budget_s),
                     "last_exec_new_confirmation": newly})

fc_new = pd.DataFrame(rows)
fc_path = os.path.join(OUT_R, "overtime_final_execution_check.csv")
if have_npz:
    fc_new.to_csv(fc_path, index=False, float_format="%.6g")
    fc = fc_new
else:
    # verify the Amini rows against the shipped file and keep it intact
    fc = pd.read_csv(fc_path)
    am_new = fc_new[fc_new.benchmark == BENCH["amini"]].copy()
    am_old = fc[fc.benchmark == BENCH["amini"]].copy()
    merged = am_new.merge(
        am_old, on=["benchmark", "unit", "rep", "budget"],
        suffixes=("_re", "_st"))
    n_flag = int((merged.last_exec_new_confirmation_re
                  != merged.last_exec_new_confirmation_st).sum())
    n_time = int((merged.abs_time_diff_re > 1e-6).sum())
    print(f"amini final-exec rows verified against shipped file: "
          f"{len(merged)} rows; flag mismatches: {n_flag}; "
          f"time mismatches: {n_time}", flush=True)
    assert n_flag == 0 and n_time == 0, \
        "Amini final-exec regeneration does not match the shipped file"
    print("sensodat final-exec rows SKIPPED: data/sensodat_fresh.npz is "
          "the full archive is shipped; this audit leaves it intact.",
          flush=True)

per_b = (fc.groupby("benchmark")
           .agg(n=("unit", "size"),
                n_ot=("overtime_s", lambda x: int((x > 0).sum())),
                last_overrun=("last_exec_overrun", "sum"),
                last_new_conf=("last_exec_new_confirmation", "sum"),
                max_ot_s=("overtime_s", "max")))
hits = fc[fc.last_exec_new_confirmation]

log("## Final overrun execution and confirmation")
log()
log("### ReproAlloc decision logs, all main budgets (both benchmarks)")
log()
log("Per-execution time was reconstructed from the recorded durations")
log("(Amini: seed-specific pool order rebuilt from the frozen harness seed;")
log("SensoDat: deterministic recorded duration per scenario). The")
log("reconstruction matches the stored per-run total time and execution")
log(f"count for every run (max abs diff {fc.abs_time_diff.max():.1e} s;")
log(f"exec-count mismatches {int((fc.exec_count_match==0).sum())}).")
log()
for b, r in per_b.iterrows():
    log(f"- {b}: {int(r['n'])} runs; final execution overran budget in "
        f"{int(r['last_overrun'])} runs; final execution added a "
        f"confirmation in {int(r['last_new_conf'])} runs "
        f"(max overtime {r['max_ot_s']:.1f} s = {r['max_ot_s']/3600:.4f} h).")
log()
log("Runs in which the final execution added a confirmation:")
log()
log("| benchmark | unit | rep | budget | overtime (s) |")
log("|---|---|---|---|---|")
for _, r in hits.iterrows():
    log(f"| {r.benchmark} | {int(r.unit)} | {int(r.rep)} | "
        f"{r.budget*100:.0f}% | {r.overtime_s:.1f} |")
log()

# ----------------------- 3. all schedulers, Amini 20% replay traces ----------
visits_path = os.path.join(EV, "_replay_visits_20pct.csv")
if not os.path.exists(visits_path):
    print("Part 3 SKIPPED: results/engineering_value_check/"
          "_replay_visits_20pct.csv is absent. Run "
          "scripts/build_engineering_value.py first (offline, from "
          "shipped data) to regenerate it.", flush=True)
    out = None
else:
    d = pd.read_csv(visits_path)
    osc_am = pd.read_csv(os.path.join(OSCD, "amini_osc_check.csv"))
    budget_map = {}
    for src in (main_am, osc_am):
        for _, r in src[src.budget_frac == 0.20].iterrows():
            budget_map[(r["method"], int(r.seed))] = (float(r.budget_s),
                                                      float(r.time_used_s))
    rows3 = []
    for (hm, seed), gg in d.groupby(["harness_method", "seed"]):
        gg = gg.sort_values("exec_idx")
        key = (hm, int(seed))
        if key not in budget_map:
            continue
        budget_s, time_used_main = budget_map[key]
        last = gg.iloc[-1]
        prev_total = gg.confirmed_total.iloc[-2] if len(gg) > 1 else 0
        newly = int(last.confirmed_total > prev_total)
        rows3.append({
            "method_harness": hm, "method": RENAME.get(hm, hm),
            "seed": int(seed), "budget": 0.20, "budget_s": budget_s,
            "time_used_trace": last.cum_time_s,
            "time_used_main_csv": time_used_main,
            "abs_time_diff": abs(last.cum_time_s - time_used_main),
            "overtime_s": last.cum_time_s - budget_s,
            "last_exec_overrun": bool(last.cum_time_s > budget_s),
            "confirmed_total_final": int(last.confirmed_total),
            "last_exec_new_confirmation": newly,
        })
    out = pd.DataFrame(rows3)
    out = out[~out.method.isin(DROP)].sort_values(["method", "seed"])
    out.to_csv(os.path.join(OUT_R,
                            "overtime_final_execution_check_amini20.csv"),
               index=False, float_format="%.6g")
    summ = (out.groupby("method")
            .agg(n=("seed", "size"),
                 n_overrun=("last_exec_overrun", "sum"),
                 last_new_conf=("last_exec_new_confirmation", "sum"),
                 max_ot_s=("overtime_s", "max")))

    log("### All schedulers, Amini-TransFuser 20% budget "
        "(full replay traces)")
    log()
    log("The stored per-execution replay traces of the engineering-time")
    log("analysis cover every scheduler at the 20% budget. Trace totals")
    log(f"match the main CSV (max abs diff {out.abs_time_diff.max():.1e} s).")
    log()
    log("| method | runs | final exec overran | final exec added "
        "confirmation |")
    log("|---|---|---|---|")
    for m, r in summ.iterrows():
        log(f"| {m} | {int(r['n'])} | {int(r['n_overrun'])} "
            f"| {int(r['last_new_conf'])} |")
    log()
    # cross-validation vs decision-log result for ReproAlloc @20%
    ra20 = fc[(fc.benchmark == "Amini-TransFuser") & (fc.budget == 0.20)]
    x = out[out.method == "ReproAlloc"].sort_values("seed")[
        "last_exec_new_confirmation"].values
    y = ra20.sort_values("unit")["last_exec_new_confirmation"].values
    xok = bool((x == y).all())
    print(f"cross-check ReproAlloc@20%: replay-trace flags == "
          f"decision-log flags: {xok}", flush=True)
    assert xok, "ReproAlloc@20% replay-trace flags differ from decision logs"

log("Scope note: per-execution decision logs exist for the optimistic")
log("selector (paper ReproAlloc) on both benchmarks and for every scheduler")
log("in the Amini 20% replay traces. SensoDat non-ReproAlloc schedulers")
log("have no stored per-execution trace; their overtime statistics are")
log("reported above from the per-run result files.")

with open(os.path.join(OUT_REP, "overtime_audit.md"), "w",
          encoding="utf-8") as f:
    f.write("\n".join(L) + "\n")
print("\nwrote", os.path.join(OUT_R, "overtime_audit.csv"))
print("wrote", os.path.join(OUT_REP, "overtime_audit.md"), flush=True)
